@extends('layouts.app', ['title' => 'Team & Access — Docs', 'heading' => 'Documentation'])

@section('content')
<div class="docs-layout">
    @include('app.docs._sidebar')

    <div class="docs-content">
        <div class="docs-hero">
            <p class="eyebrow">Documentation › Team & Access</p>
            <h2><i class="fa-solid fa-user-lock"></i> Team & Access</h2>
            <p>Control your team's workflows, track every system change, and monitor login activity for security and compliance.</p>
        </div>

        <div class="docs-req" style="margin-bottom:20px">
            <span class="docs-req-pill"><i class="fa-solid fa-key"></i> Permission: team.manage</span>
        </div>

        {{-- Approval Workflows --}}
        <div class="docs-section" id="approval-workflows">
            <div class="docs-section-title"><i class="fa-solid fa-code-branch"></i> Approval Workflows</div>
            <div class="docs-section-subtitle">Define multi-step approval chains for specific modules and transaction types.</div>
            <div class="docs-steps">
                <div class="docs-step"><div class="docs-step-num">1</div><div class="docs-step-body"><strong>Go to <a href="{{ route('team-access.approval-workflows') }}">Team Access → Approval Workflows</a></strong><p>Click "New Workflow".</p></div></div>
                <div class="docs-step"><div class="docs-step-num">2</div><div class="docs-step-body"><strong>Set the workflow name and module</strong><p>Modules: Purchasing, Sales, Inventory, Finance, General.</p></div></div>
                <div class="docs-step"><div class="docs-step-num">3</div><div class="docs-step-body"><strong>Set the trigger event and minimum amount</strong><p>Example: "Trigger on PO creation when amount ≥ Rp 10,000,000".</p></div></div>
                <div class="docs-step"><div class="docs-step-num">4</div><div class="docs-step-body"><strong>Add approvers</strong><p>Select the user IDs of approvers in order. Step 1 approver must act before Step 2 is notified.</p></div></div>
                <div class="docs-step"><div class="docs-step-num">5</div><div class="docs-step-body"><strong>Activate</strong><p>Toggle the workflow to active. It will now intercept matching transactions and create approval requests.</p></div></div>
            </div>
            <div class="docs-tip"><i class="fa-solid fa-lightbulb"></i> You can have multiple workflows per module with different amount thresholds.</div>
        </div>

        {{-- Approval Requests --}}
        <div class="docs-section" id="approval-requests">
            <div class="docs-section-title"><i class="fa-solid fa-inbox"></i> Approval Requests</div>
            <div class="docs-section-subtitle">Review and action pending approval requests generated by active workflows.</div>
            <div class="docs-steps">
                <div class="docs-step"><div class="docs-step-num">1</div><div class="docs-step-body"><strong>Go to <a href="{{ route('team-access.approval-requests') }}">Approval Requests</a></strong><p>Requests pending your action are highlighted.</p></div></div>
                <div class="docs-step"><div class="docs-step-num">2</div><div class="docs-step-body"><strong>Review the request</strong><p>See the requester, amount, reference, and workflow step you are on.</p></div></div>
                <div class="docs-step"><div class="docs-step-num">3</div><div class="docs-step-body"><strong>Click Approve, Reject, or Cancel</strong><p><em>Approve</em> advances to the next step (or completes). <em>Reject</em> stops the workflow. <em>Cancel</em> voids without prejudice.</p></div></div>
            </div>
            <div class="docs-warn"><i class="fa-solid fa-triangle-exclamation"></i> Only the designated approver for the current step can approve or reject a request.</div>
        </div>

        {{-- Audit Log --}}
        <div class="docs-section" id="audit-log">
            <div class="docs-section-title"><i class="fa-solid fa-shield-halved"></i> Audit Log</div>
            <div class="docs-section-subtitle">Immutable record of every create, update, and delete action across the system.</div>
            <div class="docs-steps">
                <div class="docs-step"><div class="docs-step-num">1</div><div class="docs-step-body"><strong>Go to <a href="{{ route('team-access.audit-log') }}">Audit Log</a></strong><p>Every system event is recorded: who did what, when, and what changed.</p></div></div>
                <div class="docs-step"><div class="docs-step-num">2</div><div class="docs-step-body"><strong>Filter by event type or model</strong><p>Narrow down to <em>created</em>, <em>updated</em>, <em>deleted</em> events or filter by specific model types (Product, Invoice, etc.).</p></div></div>
                <div class="docs-step"><div class="docs-step-num">3</div><div class="docs-step-body"><strong>View changes</strong><p>Expand a row to see <em>Old Values</em> vs. <em>New Values</em> for update events — a full before/after diff.</p></div></div>
            </div>
            <div class="docs-tip"><i class="fa-solid fa-lightbulb"></i> Audit logs cannot be deleted or modified by any user, including the owner. They are an immutable trail.</div>
        </div>

        {{-- Login History --}}
        <div class="docs-section" id="login-history">
            <div class="docs-section-title"><i class="fa-solid fa-right-to-bracket"></i> Login History</div>
            <div class="docs-section-subtitle">See every login and logout event for all users, including failed attempts.</div>
            <div class="docs-steps">
                <div class="docs-step"><div class="docs-step-num">1</div><div class="docs-step-body"><strong>Go to <a href="{{ route('team-access.login-history') }}">Login History</a></strong><p>Login and logout events are shown with IP address, device, and timestamp.</p></div></div>
                <div class="docs-step"><div class="docs-step-num">2</div><div class="docs-step-body"><strong>Review failed logins</strong><p>Failed attempts are marked with a red badge. Multiple failures from the same IP may indicate a brute-force attempt.</p></div></div>
                <div class="docs-step"><div class="docs-step-num">3</div><div class="docs-step-body"><strong>Session duration</strong><p>For completed sessions, the duration column shows how long the user was logged in.</p></div></div>
            </div>
        </div>

        {{-- Activity Log --}}
        <div class="docs-section" id="activity-log">
            <div class="docs-section-title"><i class="fa-solid fa-chart-line"></i> Activity Tracking</div>
            <div class="docs-section-subtitle">High-level summary of user actions: what each team member has been doing in the system.</div>
            <div class="docs-steps">
                <div class="docs-step"><div class="docs-step-num">1</div><div class="docs-step-body"><strong>Go to <a href="{{ route('team-access.activity-log') }}">Activity Log</a></strong><p>Chronological list of all recorded actions (login, logout, create, update, delete) per user.</p></div></div>
                <div class="docs-step"><div class="docs-step-num">2</div><div class="docs-step-body"><strong>Filter by user or action type</strong><p>Use the filter bar to focus on a specific team member or action category.</p></div></div>
                <div class="docs-step"><div class="docs-step-num">3</div><div class="docs-step-body"><strong>Compare with Audit Log</strong><p>Activity Log gives the high-level "who did what". Audit Log provides the detailed field-level diff.</p></div></div>
            </div>
        </div>
    </div>
</div>
@endsection
